/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppCoachTrainers {}
  interface AppCoachTrainersAttributes extends StencilHTMLAttributes {}

  interface AppEvents {}
  interface AppEventsAttributes extends StencilHTMLAttributes {}

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppInGameTrades {}
  interface AppInGameTradesAttributes extends StencilHTMLAttributes {}

  interface AppMasterTrainers {}
  interface AppMasterTrainersAttributes extends StencilHTMLAttributes {}

  interface AppMegastones {}
  interface AppMegastonesAttributes extends StencilHTMLAttributes {}

  interface AppOutfits {}
  interface AppOutfitsAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'name': string;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AppTmCollection {}
  interface AppTmCollectionAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppCoachTrainers': Components.AppCoachTrainers;
    'AppEvents': Components.AppEvents;
    'AppHome': Components.AppHome;
    'AppInGameTrades': Components.AppInGameTrades;
    'AppMasterTrainers': Components.AppMasterTrainers;
    'AppMegastones': Components.AppMegastones;
    'AppOutfits': Components.AppOutfits;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'AppTmCollection': Components.AppTmCollection;
  }

  interface StencilIntrinsicElements {
    'app-coach-trainers': Components.AppCoachTrainersAttributes;
    'app-events': Components.AppEventsAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-in-game-trades': Components.AppInGameTradesAttributes;
    'app-master-trainers': Components.AppMasterTrainersAttributes;
    'app-megastones': Components.AppMegastonesAttributes;
    'app-outfits': Components.AppOutfitsAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'app-tm-collection': Components.AppTmCollectionAttributes;
  }


  interface HTMLAppCoachTrainersElement extends Components.AppCoachTrainers, HTMLStencilElement {}
  var HTMLAppCoachTrainersElement: {
    prototype: HTMLAppCoachTrainersElement;
    new (): HTMLAppCoachTrainersElement;
  };

  interface HTMLAppEventsElement extends Components.AppEvents, HTMLStencilElement {}
  var HTMLAppEventsElement: {
    prototype: HTMLAppEventsElement;
    new (): HTMLAppEventsElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppInGameTradesElement extends Components.AppInGameTrades, HTMLStencilElement {}
  var HTMLAppInGameTradesElement: {
    prototype: HTMLAppInGameTradesElement;
    new (): HTMLAppInGameTradesElement;
  };

  interface HTMLAppMasterTrainersElement extends Components.AppMasterTrainers, HTMLStencilElement {}
  var HTMLAppMasterTrainersElement: {
    prototype: HTMLAppMasterTrainersElement;
    new (): HTMLAppMasterTrainersElement;
  };

  interface HTMLAppMegastonesElement extends Components.AppMegastones, HTMLStencilElement {}
  var HTMLAppMegastonesElement: {
    prototype: HTMLAppMegastonesElement;
    new (): HTMLAppMegastonesElement;
  };

  interface HTMLAppOutfitsElement extends Components.AppOutfits, HTMLStencilElement {}
  var HTMLAppOutfitsElement: {
    prototype: HTMLAppOutfitsElement;
    new (): HTMLAppOutfitsElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppTmCollectionElement extends Components.AppTmCollection, HTMLStencilElement {}
  var HTMLAppTmCollectionElement: {
    prototype: HTMLAppTmCollectionElement;
    new (): HTMLAppTmCollectionElement;
  };

  interface HTMLElementTagNameMap {
    'app-coach-trainers': HTMLAppCoachTrainersElement
    'app-events': HTMLAppEventsElement
    'app-home': HTMLAppHomeElement
    'app-in-game-trades': HTMLAppInGameTradesElement
    'app-master-trainers': HTMLAppMasterTrainersElement
    'app-megastones': HTMLAppMegastonesElement
    'app-outfits': HTMLAppOutfitsElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'app-tm-collection': HTMLAppTmCollectionElement
  }

  interface ElementTagNameMap {
    'app-coach-trainers': HTMLAppCoachTrainersElement;
    'app-events': HTMLAppEventsElement;
    'app-home': HTMLAppHomeElement;
    'app-in-game-trades': HTMLAppInGameTradesElement;
    'app-master-trainers': HTMLAppMasterTrainersElement;
    'app-megastones': HTMLAppMegastonesElement;
    'app-outfits': HTMLAppOutfitsElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'app-tm-collection': HTMLAppTmCollectionElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
